* About
Rofi Script Collection is a collection of scripts and their execution using a tool called =Rofi=. =Rofi= provides the user with a prompt to select the script to execute.
* Requirements
- =rofi=
  - Debian (Ubuntu, Mint etc)
    - =sudo apt install rofi=
  - Arch
    - =sudo pacman -S rofi=
  - Fedora
    - =sudo dnf install rofi=
  - [[https://search.nixos.org/packages?channel=22.11&from=0&size=50&sort=relevance&type=packages&query=rofi][Nix]]
- =git=
  - Debian (Ubuntu, Mint etc)
    - =sudo apt install git=
  - Arch
    - =sudo pacman -S git=
  - Fedora
    - =sudo dnf install git=
  - [[https://search.nixos.org/packages?channel=22.11&from=0&size=50&sort=relevance&type=packages&query=git][Nix]]
* Installation
- Step 1: Install =rofi= and =git=

- Step 2: Clone the repository and go into it
#+BEGIN_SRC sh
git clone https://github.com/AfzGit/rofi-scripts-collection
#+END_SRC

- Step 3: Place the =rofi-scripts= folder wherever you want and give it execution permissions recursively.
#+BEGIN_SRC sh
# granting execution permission to the scripts in the folder
chmod 755 -R rofi-scripts-collection/rofi-scripts/

# Placing in home folder
mv rofi-scripts-collection/rofi-scripts/ ~

# Removing uneeded files
rm -r rofi-scripts-collection/
#+END_SRC

- Step 4: Now add the shortcut to trigger rofi in your system settings (Check your desktop Environment's custom shortcuts settings)
#+BEGIN_SRC sh
bash ~/rofi-scripts/$(ls -1 ~/rofi-scripts/ | rofi -scroll-method 1 -dmenu -i -p "Run:")
#+END_SRC

- Step 5: The installation has been done, now just press the shortcut key you assigned for the command above. To add more scripts, just put them in the =rofi-scripts= folder.
* Notes
If your system runs FISH shell by default, use this shortcut instead for Step 4:
#+BEGIN_SRC sh
set -x selected (ls -1 ~/rofi-scripts/ | rofi -scroll-method 1 -dmenu -i -p "Run:") && bash ~/rofi-scripts/$selected
#+END_SRC
